export type LandingDemoVariant = 'signal' | 'blueprint' | 'lanes' | 'community';
export type LandingBackgroundGlyphShape = 'circle';

export interface LandingStoryScene {
  id: string;
  eyebrow: string;
  headline: string;
  subheadline: string;
  demoVariant: LandingDemoVariant;
  accentClass: string;
}

export interface LandingStep {
  id: string;
  title: string;
  description: string;
}

export interface LandingValuePoint {
  id: string;
  title: string;
  description: string;
}

export interface LandingBlueprintPreview {
  id: string;
  title: string;
  creator: string;
  channel: string;
  thumbnailUrl: string;
  summary: string;
  takeaways: string[];
  statsLabel: string;
}

export interface LandingBackgroundGlyph {
  id: string;
  shape: LandingBackgroundGlyphShape;
  left: string;
  top: string;
  size: number;
  mobileSize?: number;
  depth: 'far' | 'mid' | 'near';
  toneClassName: string;
  desktopOnly?: boolean;
  desktopPath: string;
  mobilePath?: string;
  startProgress?: number;
  endProgress?: number;
  startRotate?: number;
  endRotate?: number;
  startScale?: number;
  endScale?: number;
  startOpacity?: number;
  endOpacity?: number;
}

export const LANDING_STORY_SCENES: LandingStoryScene[] = [
  {
    id: 'signal-buried',
    eyebrow: 'Too much to watch',
    headline: 'YouTube is full of value. Most of it gets buried.',
    subheadline:
      'Great videos compete with endless watch time. Bleup turns the ones worth keeping into blueprints.',
    demoVariant: 'signal',
    accentClass: 'from-primary/25 via-amber-200/30 to-orange-300/20',
  },
  {
    id: 'blueprint-fast',
    eyebrow: 'Scan, do, move on',
    headline: 'Bleup turns long videos into blueprints you can scan in seconds.',
    subheadline:
      'Instead of rewatching or scrubbing timestamps, get the structure, takeaways, and next steps in one place.',
    demoVariant: 'blueprint',
    accentClass: 'from-orange-300/20 via-primary/15 to-amber-200/30',
  },
  {
    id: 'sources-and-topics',
    eyebrow: 'Personalized discovery',
    headline: "Get your favorite creators' new videos as blueprints.",
    subheadline:
      'Keep up with the creators you trust and discover more around the topics you care about.',
    demoVariant: 'lanes',
    accentClass: 'from-primary/20 via-rose-200/20 to-amber-100/30',
  },
  {
    id: 'community-payoff',
    eyebrow: 'Stay current without the hours',
    headline: 'Find the best new videos without spending hours watching everything.',
    subheadline:
      'One unlock can help everyone. Bleup turns good finds into reusable knowledge and better discovery.',
    demoVariant: 'community',
    accentClass: 'from-amber-200/30 via-primary/15 to-orange-200/25',
  },
];

export const LANDING_HOW_IT_WORKS: LandingStep[] = [
  {
    id: 'follow',
    title: 'Follow the right creators',
    description: 'Follow creators you trust so their new uploads land in your feed.',
  },
  {
    id: 'generate',
    title: 'Generate a blueprint',
    description: 'Turn long videos into structured blueprints you can scan in seconds.',
  },
  {
    id: 'discover',
    title: 'Discover by topic',
    description: 'Join Bleup channels to browse the best published blueprints by interest.',
  },
];

export const LANDING_VALUE_POINTS: LandingValuePoint[] = [
  {
    id: 'consume-less',
    title: 'Spend less time watching',
    description: 'Understand the core without sitting through every full video end to end.',
  },
  {
    id: 'discover-better',
    title: 'Discover better creators',
    description: 'Use channels and community signals to find videos you would not have discovered from follows alone.',
  },
  {
    id: 'reuse-what-works',
    title: 'Keep what is worth revisiting',
    description: 'Turn the best videos into reusable notes, routines, and shared reference points.',
  },
];

export const LANDING_BLUEPRINT_PREVIEWS: LandingBlueprintPreview[] = [
  {
    id: 'leucine-after-35',
    title: 'Leucine After 35: Better for Muscle Maintenance Than Muscle Gain',
    creator: 'Thomas DeLauer',
    channel: 'longevity-health-aging',
    thumbnailUrl: 'https://i.ytimg.com/vi/IherD4otL2I/hqdefault.jpg',
    summary:
      'Use leucine as a maintenance lever first, not a hypertrophy shortcut. The strongest case is preserving muscle function as you age, especially when protein intake is inconsistent.',
    takeaways: [
      'Use leucine for maintenance and function, not as a growth hack',
      'Meal-timed dosing matters more than random use',
      'It helps most when baseline protein intake is only moderate',
    ],
    statsLabel: '7 min scan',
  },
  {
    id: 'agents-context-files',
    title: 'Autogenerated AGENTS.md Files Can Hurt Coding Agent Performance',
    creator: 'Research example',
    channel: 'ai-tools-automation',
    thumbnailUrl: 'https://i.ytimg.com/vi/s95ISC-KeIM/hqdefault.jpg',
    summary:
      'Treat autogenerated repo context files as a high-variance tool. The practical takeaway is to keep guidance narrow, measure success against cost, and avoid over-scoped instruction payloads.',
    takeaways: [
      'More context did not automatically improve agent performance',
      'Human-written guidance helped only modestly in most repos',
      'Context files are most useful when baseline docs are weak',
    ],
    statsLabel: '5 min scan',
  },
  {
    id: 'italian-sausage-chowder',
    title: 'Italian Sausage Chowder (Shellfish-Friendly Option)',
    creator: 'Cooking example',
    channel: 'cooking-home-kitchen',
    thumbnailUrl: 'https://i.ytimg.com/vi/Fjng4WHkJ6E/hqdefault.jpg',
    summary:
      'Build this as a cold-weather comfort chowder with strong texture and substitution control. The blueprint keeps the useful decisions and fallback fixes visible at a glance.',
    takeaways: [
      'Keep sausage in medium chunks for the best texture payoff',
      'Finish with hot milk for a smoother final body',
      'Use broth swaps and seasoning adjustments as quick recovery levers',
    ],
    statsLabel: '6 min scan',
  },
];

export const LANDING_BACKGROUND_GLYPHS: LandingBackgroundGlyph[] = [
  {
    id: 'glyph-circle-top-long-a',
    shape: 'circle',
    left: '6%',
    top: '7%',
    size: 132,
    mobileSize: 60,
    depth: 'far',
    toneClassName: 'bg-orange-300/92 shadow-[0_0_80px_rgba(251,146,60,0.42)]',
    desktopPath: 'M 6 10 C 20 2, 38 12, 56 8 C 70 6, 82 9, 94 14',
    mobilePath: 'M 8 10 C 16 6, 26 12, 38 9 C 48 7, 58 9, 68 13',
    startProgress: 0.04,
    endProgress: 0.96,
    startScale: 0.94,
    endScale: 1.08,
    startOpacity: 0.6,
    endOpacity: 0.88,
  },
  {
    id: 'glyph-circle-top-long-b',
    shape: 'circle',
    left: '90%',
    top: '18%',
    size: 108,
    mobileSize: 48,
    depth: 'far',
    toneClassName: 'bg-amber-200/94 shadow-[0_0_82px_rgba(252,211,77,0.36)]',
    desktopPath: 'M 94 22 C 78 14, 58 24, 40 18 C 28 15, 18 18, 7 22',
    mobilePath: 'M 88 22 C 74 16, 58 22, 42 18 C 30 16, 20 18, 10 21',
    startProgress: 0.04,
    endProgress: 0.96,
    startScale: 0.92,
    endScale: 1.1,
    startOpacity: 0.54,
    endOpacity: 0.82,
  },
  {
    id: 'glyph-circle-bottom-medium-a',
    shape: 'circle',
    left: '5%',
    top: '78%',
    size: 92,
    mobileSize: 44,
    depth: 'mid',
    toneClassName: 'bg-primary/78 shadow-[0_0_66px_rgba(168,85,247,0.32)]',
    desktopPath: 'M 4 78 C 14 84, 28 80, 40 74 C 48 70, 56 70, 64 73',
    mobilePath: 'M 6 80 C 14 84, 24 80, 34 76 C 42 73, 50 73, 58 76',
    startProgress: 0.06,
    endProgress: 0.78,
    startScale: 0.96,
    endScale: 1.1,
    startOpacity: 0.58,
    endOpacity: 0.8,
  },
  {
    id: 'glyph-circle-bottom-medium-b',
    shape: 'circle',
    left: '92%',
    top: '76%',
    size: 108,
    mobileSize: 50,
    depth: 'mid',
    toneClassName: 'bg-rose-200/90 shadow-[0_0_62px_rgba(251,113,133,0.32)]',
    desktopPath: 'M 94 78 C 92 68, 86 60, 78 56 C 72 53, 66 54, 60 60',
    mobilePath: 'M 90 80 C 88 70, 82 64, 74 60 C 68 57, 62 58, 56 63',
    startProgress: 0.05,
    endProgress: 0.76,
    startScale: 0.94,
    endScale: 1.08,
    startOpacity: 0.5,
    endOpacity: 0.76,
  },
  {
    id: 'glyph-circle-top-right-short',
    shape: 'circle',
    left: '96%',
    top: '9%',
    size: 58,
    mobileSize: 30,
    depth: 'far',
    toneClassName: 'bg-sky-200/84 shadow-[0_0_40px_rgba(125,211,252,0.26)]',
    desktopPath: 'M 96 12 C 93 8, 88 8, 84 12 C 87 16, 92 18, 95 15',
    mobilePath: 'M 92 14 C 89 10, 84 10, 80 13 C 83 17, 88 18, 91 16',
    startProgress: 0.12,
    endProgress: 0.38,
    startScale: 0.98,
    endScale: 1.04,
    startOpacity: 0.46,
    endOpacity: 0.68,
  },
];
