import fs from "node:fs";
import path from "node:path";

type PersonaRegistryV0 = {
  version: 0;
  personas: Array<{
    id: string;
    auth_env_path?: string;
  }>;
};

type SeedSecretsV0 = {
  version: 0;
  personas: Record<string, { email: string; password: string }>;
};

function die(msg: string): never {
  process.stderr.write(msg.endsWith("\n") ? msg : msg + "\n");
  process.exit(1);
}

function ensureDir(dirPath: string) {
  fs.mkdirSync(dirPath, { recursive: true });
}

function writeEnvFile(envPath: string, email: string, password: string) {
  ensureDir(path.dirname(envPath));
  const out = [
    "# Generated by seed/scripts/sync_persona_auth_env.ts",
    "# Do not commit. This file contains credentials.",
    `SEED_USER_EMAIL=${email}`,
    `SEED_USER_PASSWORD=${password}`,
    "",
  ].join("\n");
  fs.writeFileSync(envPath, out, "utf8");
}

function main() {
  const cwd = process.cwd();
  const registryPath = process.argv[2] || path.join("seed", "persona_registry_v0.json");
  const secretsPath = process.argv[3] || path.join("seed", "secrets.local.json");

  if (!fs.existsSync(registryPath)) die(`persona registry not found: ${registryPath}`);
  const reg = JSON.parse(fs.readFileSync(registryPath, "utf8")) as PersonaRegistryV0;
  if (!reg || reg.version !== 0 || !Array.isArray(reg.personas)) die("persona registry must be version 0 with personas[]");

  if (!fs.existsSync(secretsPath)) {
    die(
      [
        `secrets json not found: ${secretsPath}`,
        "Create seed/secrets.local.json (gitignored) with:",
        '{ "version": 0, "personas": { "persona_id": { "email": "...", "password": "..." } } }',
      ].join("\n")
    );
  }
  const secrets = JSON.parse(fs.readFileSync(secretsPath, "utf8")) as SeedSecretsV0;
  if (!secrets || secrets.version !== 0 || !secrets.personas || typeof secrets.personas !== "object") {
    die("secrets json must be version 0 with personas{persona_id:{email,password}}");
  }

  const written: string[] = [];
  const missing: string[] = [];
  for (const p of reg.personas) {
    const envPath = String(p.auth_env_path || "").trim();
    if (!envPath) continue;
    const rec = (secrets.personas as any)[p.id];
    const email = String(rec?.email || "").trim();
    const password = String(rec?.password || "").trim();
    if (!email || !password) {
      missing.push(p.id);
      continue;
    }
    writeEnvFile(envPath, email, password);
    written.push(path.relative(cwd, envPath).replace(/\\/g, "/"));
  }

  if (missing.length) {
    die(
      [
        "missing persona credentials in seed/secrets.local.json for:",
        ...missing.map((id) => `- ${id}`),
      ].join("\n")
    );
  }

  if (!written.length) {
    process.stdout.write("No env files written (no personas had auth_env_path).\n");
    return;
  }

  process.stdout.write("Wrote persona auth env files:\n");
  for (const p of written) process.stdout.write(`- ${p}\n`);
}

main();
