import fs from "node:fs";
import path from "node:path";

type PersonaRegistryV0 = {
  version: 0;
  personas: Array<{
    id: string;
    auth_creds_slot?: number;
    auth_env_path?: string;
  }>;
};

function die(msg: string): never {
  process.stderr.write(msg.endsWith("\n") ? msg : msg + "\n");
  process.exit(1);
}

function readLines(filePath: string): string[] {
  if (!fs.existsSync(filePath)) return [];
  const raw = fs.readFileSync(filePath, "utf8");
  return raw
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith("#"));
}

function ensureDir(dirPath: string) {
  fs.mkdirSync(dirPath, { recursive: true });
}

function writeEnvFile(envPath: string, email: string, password: string) {
  ensureDir(path.dirname(envPath));
  const out = [
    "# Generated by seed/scripts/sync_persona_auth_env.ts",
    "# Do not commit. This file contains credentials.",
    `SEED_USER_EMAIL=${email}`,
    `SEED_USER_PASSWORD=${password}`,
    "",
  ].join("\n");
  fs.writeFileSync(envPath, out, "utf8");
}

function main() {
  const cwd = process.cwd();
  const registryPath = process.argv[2] || path.join("seed", "persona_registry_v0.json");
  const secretsPath = process.argv[3] || ".secrets.local";

  if (!fs.existsSync(registryPath)) die(`persona registry not found: ${registryPath}`);
  const reg = JSON.parse(fs.readFileSync(registryPath, "utf8")) as PersonaRegistryV0;
  if (!reg || reg.version !== 0 || !Array.isArray(reg.personas)) die("persona registry must be version 0 with personas[]");

  const lines = readLines(secretsPath);
  if (lines.length < 2) die(`secrets file must contain at least 2 non-empty lines: ${secretsPath}`);

  const pairCount = Math.floor(lines.length / 2);
  const getPair = (slot: number) => {
    const s = Number(slot);
    if (!Number.isFinite(s) || s < 0 || s >= pairCount) return null;
    const email = String(lines[s * 2] || "").trim();
    const password = String(lines[s * 2 + 1] || "").trim();
    if (!email || !password) return null;
    return { email, password };
  };

  const written: string[] = [];
  for (const p of reg.personas) {
    const envPath = String(p.auth_env_path || "").trim();
    const slot = p.auth_creds_slot;
    if (!envPath || slot === undefined || slot === null) continue;
    const pair = getPair(slot);
    if (!pair) die(`missing creds for persona ${p.id}: auth_creds_slot=${String(slot)}`);
    writeEnvFile(envPath, pair.email, pair.password);
    written.push(path.relative(cwd, envPath).replace(/\\/g, "/"));
  }

  if (!written.length) {
    process.stdout.write("No env files written (no personas had auth_env_path + auth_creds_slot).\n");
    return;
  }

  process.stdout.write("Wrote persona auth env files:\n");
  for (const p of written) process.stdout.write(`- ${p}\n`);
}

main();

